<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<?php $helper = $this->helper('Scommerce\LazyLoading\Helper\Data') ?>
<img class="photo image"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
